package main

// Guards license delivery across the release configuration: every artifact
// GoReleaser publishes must carry LICENSE (Apache-2.0), NOTICE, and the
// licenses/ tree of third-party texts, and the package-manager metadata must
// name the Apache-2.0 license accurately. These assertions parse
// .goreleaser.yaml so formatting changes don't break them, only real
// delivery regressions do — and they pin exact src/dst pairs and statement
// lines (not just substrings) so a future config break cannot slip past.

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

type releaseFileEntry struct {
	Src string `yaml:"src"`
	Dst string `yaml:"dst"`
}

type releaseConfig struct {
	Archives []struct {
		ID    string      `yaml:"id"`
		Files []yaml.Node `yaml:"files"`
	} `yaml:"archives"`
	NFPMs []struct {
		ID       string `yaml:"id"`
		License  string `yaml:"license"`
		Contents []struct {
			Src  string `yaml:"src"`
			Dst  string `yaml:"dst"`
			Type string `yaml:"type"`
		} `yaml:"contents"`
	} `yaml:"nfpms"`
	Brews []struct {
		Name         string  `yaml:"name"`
		Description  string  `yaml:"description"`
		License      *string `yaml:"license"`
		Install      string  `yaml:"install"`
		ExtraInstall string  `yaml:"extra_install"`
	} `yaml:"brews"`
	Scoops []struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
		License     string `yaml:"license"`
	} `yaml:"scoops"`
	Winget []struct {
		Name             string `yaml:"name"`
		ShortDescription string `yaml:"short_description"`
		Description      string `yaml:"description"`
		License          string `yaml:"license"`
		LicenseURL       string `yaml:"license_url"`
		Copyright        string `yaml:"copyright"`
	} `yaml:"winget"`
}

// licenseDocs are the plain license files every distribution channel must
// deliver; each is tracked in the repository root, so the tests also verify
// the sources exist on disk.
var licenseDocs = []string{"LICENSE", "NOTICE"}

// apacheLicenseID is the SPDX identifier every package-manager manifest must
// carry.
const apacheLicenseID = "Apache-2.0"

func loadReleaseConfig(t *testing.T) releaseConfig {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join("..", "..", ".goreleaser.yaml"))
	if err != nil {
		t.Fatalf("reading .goreleaser.yaml: %v", err)
	}

	var config releaseConfig
	if err := yaml.Unmarshal(raw, &config); err != nil {
		t.Fatalf("parsing .goreleaser.yaml: %v", err)
	}
	return config
}

// mustStatRepoFile asserts that a path referenced by the release config
// exists in the repository root as a regular file.
func mustStatRepoFile(t *testing.T, name string) {
	t.Helper()

	info, err := os.Stat(filepath.Join("..", "..", name))
	if err != nil {
		t.Errorf("release config references %s, which does not exist in the repository root: %v", name, err)
		return
	}
	if info.IsDir() {
		t.Errorf("release config references %s as a file, but it is a directory", name)
	}
}

// checkGeneratedLicensesDir asserts that licenses/ is a directory when it is
// present. It is generated by `make licenses` (a GoReleaser before hook), so
// its absence from a fresh checkout is expected and only the config shape is
// asserted in that case.
func checkGeneratedLicensesDir(t *testing.T) {
	t.Helper()

	info, err := os.Stat(filepath.Join("..", "..", "licenses"))
	if os.IsNotExist(err) {
		t.Log("licenses/ not present locally; it is generated by `make licenses` before release builds")
		return
	}
	if err != nil {
		t.Errorf("stat licenses/: %v", err)
		return
	}
	if !info.IsDir() {
		t.Error("licenses exists in the repository root but is not a directory")
	}
}

func TestReleaseArchivesCarryLicenseSet(t *testing.T) {
	config := loadReleaseConfig(t)
	if len(config.Archives) == 0 {
		t.Fatal("no archives configured in .goreleaser.yaml")
	}

	for _, archive := range config.Archives {
		// Split the `files` list into plain string entries and src/dst
		// mappings so each requirement is asserted against the exact form it
		// must take, not a lossy flattened view.
		plain := map[string]bool{}
		var mapped []releaseFileEntry
		for _, entry := range archive.Files {
			var name string
			if err := entry.Decode(&name); err == nil {
				plain[name] = true
				continue
			}
			var fileEntry releaseFileEntry
			if err := entry.Decode(&fileEntry); err != nil {
				t.Fatalf("archive %q files entry is neither a string nor a src/dst mapping: %v", archive.ID, err)
			}
			mapped = append(mapped, fileEntry)
		}

		for _, required := range licenseDocs {
			if !plain[required] {
				t.Errorf("archive %q does not list %s as a plain file entry", archive.ID, required)
			}
		}

		licensesTree := false
		for _, entry := range mapped {
			if entry.Src == "licenses/**/*" && entry.Dst == "licenses" {
				licensesTree = true
				break
			}
		}
		if !licensesTree {
			t.Errorf("archive %q does not map the licenses/ tree (want an entry with src \"licenses/**/*\" and dst \"licenses\"; got mappings %v)", archive.ID, mapped)
		}
	}

	for _, required := range licenseDocs {
		mustStatRepoFile(t, required)
	}
	checkGeneratedLicensesDir(t)
}

func TestLinuxPackagesCarryLicenseSet(t *testing.T) {
	config := loadReleaseConfig(t)
	if len(config.NFPMs) == 0 {
		t.Fatal("no nfpms configured in .goreleaser.yaml")
	}

	required := []struct {
		src string
		dst string
		typ string
	}{
		{src: "LICENSE", dst: "/usr/share/doc/bomly/LICENSE"},
		{src: "NOTICE", dst: "/usr/share/doc/bomly/NOTICE"},
		{src: "licenses", dst: "/usr/share/doc/bomly/licenses", typ: "tree"},
	}

	for _, nfpm := range config.NFPMs {
		if nfpm.License != apacheLicenseID {
			t.Errorf("nfpm %q license = %q, want %q", nfpm.ID, nfpm.License, apacheLicenseID)
		}

		byDst := map[string]struct {
			Src  string
			Type string
		}{}
		for _, content := range nfpm.Contents {
			byDst[content.Dst] = struct {
				Src  string
				Type string
			}{Src: content.Src, Type: content.Type}
		}

		for _, want := range required {
			content, ok := byDst[want.dst]
			if !ok {
				t.Errorf("nfpm %q does not install %s", nfpm.ID, want.dst)
				continue
			}
			if content.Src != want.src {
				t.Errorf("nfpm %q installs %s from src %q, want %q", nfpm.ID, want.dst, content.Src, want.src)
			}
			if content.Type != want.typ {
				t.Errorf("nfpm %q entry for %s has type %q, want %q", nfpm.ID, want.dst, content.Type, want.typ)
			}
		}
	}

	for _, required := range licenseDocs {
		mustStatRepoFile(t, required)
	}
	checkGeneratedLicensesDir(t)
}

// hasStatementLine reports whether any line of a script block, once
// whitespace-trimmed, matches the pattern exactly. Statement-line matching
// (rather than substring search) ensures the assertion fails if a statement
// is commented out, mangled, or merely mentioned in surrounding text.
func hasStatementLine(block string, pattern *regexp.Regexp) bool {
	for _, line := range strings.Split(block, "\n") {
		if pattern.MatchString(strings.TrimSpace(line)) {
			return true
		}
	}
	return false
}

func TestHomebrewFormulaLicensing(t *testing.T) {
	config := loadReleaseConfig(t)
	if len(config.Brews) == 0 {
		t.Fatal("no brews configured in .goreleaser.yaml")
	}

	binInstall := regexp.MustCompile(`^bin\.install "bomly"$`)
	docInstall := regexp.MustCompile(`^doc\.install "[^"]+"(, "[^"]+")*$`)
	quotedArg := regexp.MustCompile(`"([^"]+)"`)

	for _, brew := range config.Brews {
		if strings.TrimSpace(brew.Description) == "" {
			t.Errorf("brew %q has an empty description", brew.Name)
		}

		if brew.License == nil || *brew.License != apacheLicenseID {
			t.Errorf("brew %q must set license %q (got %v)", brew.Name, apacheLicenseID, brew.License)
		}

		if !hasStatementLine(brew.Install, binInstall) {
			t.Errorf("brew %q install stanza lacks the statement `bin.install \"bomly\"` (install: %q)", brew.Name, brew.Install)
		}

		// Collect the arguments of every doc.install statement line; the
		// union must cover the full license set.
		docInstalled := map[string]bool{}
		for _, line := range strings.Split(brew.ExtraInstall, "\n") {
			line = strings.TrimSpace(line)
			if !docInstall.MatchString(line) {
				continue
			}
			for _, match := range quotedArg.FindAllStringSubmatch(line, -1) {
				docInstalled[match[1]] = true
			}
		}
		for _, required := range append(append([]string{}, licenseDocs...), "licenses") {
			if !docInstalled[required] {
				t.Errorf("brew %q extra_install has no doc.install statement covering %q (extra_install: %q)", brew.Name, required, brew.ExtraInstall)
			}
		}
	}
}

func TestScoopManifestLicensing(t *testing.T) {
	config := loadReleaseConfig(t)
	if len(config.Scoops) == 0 {
		t.Fatal("no scoops configured in .goreleaser.yaml")
	}

	for _, scoop := range config.Scoops {
		if scoop.License != apacheLicenseID {
			t.Errorf("scoop %q license = %q, want %q", scoop.Name, scoop.License, apacheLicenseID)
		}
		if strings.TrimSpace(scoop.Description) == "" {
			t.Errorf("scoop %q has an empty description", scoop.Name)
		}
	}
}

func TestWingetManifestLicensing(t *testing.T) {
	config := loadReleaseConfig(t)
	if len(config.Winget) == 0 {
		t.Fatal("no winget manifests configured in .goreleaser.yaml")
	}

	// The license URL must be the immutable tag-templated copy of the
	// Apache license in this repository, never a mutable main ref.
	licenseURL := regexp.MustCompile(`^https://github\.com/bomly-dev/bomly-cli/blob/\{\{ \.Tag \}\}/LICENSE$`)

	for _, manifest := range config.Winget {
		if !licenseURL.MatchString(manifest.LicenseURL) {
			t.Errorf("winget %q license_url %q is not the tag-templated LICENSE path (want match for %s)", manifest.Name, manifest.LicenseURL, licenseURL)
		}
		if manifest.License != apacheLicenseID {
			t.Errorf("winget %q license = %q, want %q", manifest.Name, manifest.License, apacheLicenseID)
		}
		if strings.TrimSpace(manifest.Copyright) == "" {
			t.Errorf("winget %q has an empty copyright field", manifest.Name)
		}
		for _, description := range []string{manifest.ShortDescription, manifest.Description} {
			if strings.TrimSpace(description) == "" {
				t.Errorf("winget %q has an empty description field", manifest.Name)
			}
		}
	}
}

// TestLicensesTargetShipsMathutilNotice guards the explicit BSD-3-Clause
// notice copy for modernc.org/mathutil: go-licenses cannot classify that
// module, so the Makefile ships its LICENSE by hand and must keep doing so
// for as long as the module is linked into the binary.
func TestLicensesTargetShipsMathutilNotice(t *testing.T) {
	makefile, err := os.ReadFile(filepath.Join("..", "..", "Makefile"))
	if err != nil {
		t.Fatalf("read Makefile: %v", err)
	}
	content := string(makefile)
	for _, required := range []string{
		"go list -m -f '{{.Dir}}' modernc.org/mathutil",
		"licenses/modernc.org/mathutil/LICENSE",
		"test -s licenses/modernc.org/mathutil/LICENSE",
	} {
		if !strings.Contains(content, required) {
			t.Errorf("Makefile licenses target is missing %q; the mathutil BSD notice must ship with binary distributions", required)
		}
	}
}
