//go:build ignore

// config_gen generates docs/CONFIG_REFERENCE.md from the resolvedConfig struct tags.
//
//go:generate go run config_gen.go
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"
)

type configField struct {
	Name       string
	YAMLKey    string
	EnvVar     string
	Doc        string
	DefaultVal string
	GoType     string
	Section    string
}

func main() {
	fields, err := parseConfigFields()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	md := renderMarkdown(fields)
	outPath := filepath.Join("..", "..", "docs", "CONFIG_REFERENCE.md")
	if err := os.WriteFile(outPath, []byte(md), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("generated %s (%d fields)\n", outPath, len(fields))
}

func parseConfigFields() ([]configField, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "config.go", nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse config.go: %w", err)
	}

	// First, build a map of field name -> yaml key from fileConfig struct.
	fileConfigYAML := map[string]string{}
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "fileConfig" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				if len(field.Names) == 0 || field.Tag == nil {
					continue
				}
				tag := strings.Trim(field.Tag.Value, "`")
				st := reflect.StructTag(tag)
				yamlKey := st.Get("yaml")
				if i := strings.Index(yamlKey, ","); i >= 0 {
					yamlKey = yamlKey[:i]
				}
				if yamlKey != "" && yamlKey != "-" {
					fileConfigYAML[field.Names[0].Name] = yamlKey
				}
			}
		}
	}

	var fields []configField
	currentSection := "General"

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "resolvedConfig" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				if field.Doc != nil {
					for _, c := range field.Doc.List {
						text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
						if text != "" && !strings.Contains(text, "`") {
							currentSection = text
						}
					}
				}
				if field.Comment != nil {
					for _, c := range field.Comment.List {
						text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
						if text != "" {
							currentSection = text
						}
					}
				}

				if len(field.Names) == 0 {
					continue
				}

				name := field.Names[0].Name
				goType := typeString(field.Type)
				tag := ""
				if field.Tag != nil {
					tag = strings.Trim(field.Tag.Value, "`")
				}

				st := reflect.StructTag(tag)
				envVar := st.Get("env")
				doc := st.Get("doc")
				defaultVal := st.Get("default")

				if doc == "" {
					continue
				}

				yamlKey := fileConfigYAML[name]
				if yamlKey == "" {
					yamlKey = toSnakeCase(name)
				}

				fields = append(fields, configField{
					Name:       name,
					YAMLKey:    yamlKey,
					EnvVar:     envVar,
					Doc:        doc,
					DefaultVal: defaultVal,
					GoType:     goType,
					Section:    currentSection,
				})
			}
		}
	}
	return fields, nil
}

func renderMarkdown(fields []configField) string {
	var b strings.Builder
	b.WriteString("# Configuration Reference\n\n")
	b.WriteString("<!-- Auto-generated by go generate. Do not edit manually. -->\n\n")
	b.WriteString("Bomly resolves configuration in the following order, with later sources overriding earlier ones:\n\n")
	b.WriteString("1. `~/.bomly/config.yaml`\n")
	b.WriteString("2. `<project>/.bomly/config.yaml`\n")
	b.WriteString("3. `BOMLY_*` environment variables\n")
	b.WriteString("4. CLI flags\n\n")
	b.WriteString("`--config <path>` adds an explicit config file to the load list before environment variables and flags are applied.\n\n")
	b.WriteString("---\n\n")

	type sectionGroup struct {
		name   string
		fields []configField
	}
	var sections []sectionGroup
	sectionIdx := map[string]int{}
	for _, f := range fields {
		idx, ok := sectionIdx[f.Section]
		if !ok {
			idx = len(sections)
			sectionIdx[f.Section] = idx
			sections = append(sections, sectionGroup{name: f.Section})
		}
		sections[idx].fields = append(sections[idx].fields, f)
	}

	for _, sec := range sections {
		b.WriteString("## " + sec.name + "\n\n")
		b.WriteString("| YAML Key | Environment Variable | Type | Default | Description |\n")
		b.WriteString("|----------|---------------------|------|---------|-------------|\n")
		for _, f := range sec.fields {
			def := f.DefaultVal
			if def == "" {
				def = "-"
			}
			env := f.EnvVar
			if env == "" {
				env = "-"
			}
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | %s | %s |\n", f.YAMLKey, env, f.GoType, def, f.Doc))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Example Configuration\n\n")
	b.WriteString("```yaml\n")
	b.WriteString("# ~/.bomly/config.yaml or .bomly/config.yaml\n")
	for _, sec := range sections {
		b.WriteString("\n# " + sec.name + "\n")
		for _, f := range sec.fields {
			val := f.DefaultVal
			if val == "" {
				switch f.GoType {
				case "bool":
					val = "false"
				case "int":
					val = "0"
				case "string":
					val = "\"\""
				case "[]string":
					val = "[]"
				default:
					val = "\"\""
				}
			}
			b.WriteString(fmt.Sprintf("# %s\n", f.Doc))
			b.WriteString(fmt.Sprintf("# %s: %s\n", f.YAMLKey, val))
		}
	}
	b.WriteString("```\n")

	return b.String()
}

func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.ArrayType:
		return "[]" + typeString(t.Elt)
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	default:
		return "any"
	}
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteByte(byte(r + 32))
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
