package python

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/bomly-dev/bomly-cli/sdk"
)

const sampleRequirementsLock = `#
# This file is autogenerated by pip-compile.
#
certifi==2024.8.30
    # via requests
charset-normalizer==2.0.12
    # via requests
django==1.11.29
    # via -r requirements.in
idna==2.8
    # via requests
requests==2.21.0
    # via -r requirements.in
urllib3==1.24.3
    # via
    #   -r requirements.in
    #   requests
pytest==7.4.3
    # via -r requirements-dev.in
`

func writeLock(t *testing.T, body string) (string, string) {
	t.Helper()
	dir := t.TempDir()
	lockPath := filepath.Join(dir, pipLockFileName)
	if err := os.WriteFile(lockPath, []byte(body), 0o644); err != nil {
		t.Fatalf("write lock: %v", err)
	}
	return lockPath, dir
}

func directDepIDs(t *testing.T, g *sdk.Graph, id string) []string {
	t.Helper()
	deps, err := g.DirectDependencies(id)
	if err != nil {
		t.Fatalf("direct deps of %s: %v", id, err)
	}
	ids := make([]string, 0, len(deps))
	for _, d := range deps {
		ids = append(ids, d.ID)
	}
	sort.Strings(ids)
	return ids
}

func TestDepGraphFromRequirementsLock(t *testing.T) {
	lockPath, dir := writeLock(t, sampleRequirementsLock)
	g, err := depGraphFromRequirementsLock(lockPath, dir)
	if err != nil {
		t.Fatalf("depGraphFromRequirementsLock: %v", err)
	}

	// Pinned versions become nodes.
	for _, want := range []string{
		"certifi@2024.8.30",
		"idna@2.8",
		"requests@2.21.0",
		"urllib3@1.24.3",
		"pytest@7.4.3",
	} {
		if _, ok := g.Node(want); !ok {
			t.Errorf("missing node %s", want)
		}
	}

	// requests pulls in its transitive deps via "# via requests".
	got := directDepIDs(t, g, "requests@2.21.0")
	want := []string{
		"certifi@2024.8.30",
		"charset-normalizer@2.0.12",
		"idna@2.8",
		"urllib3@1.24.3",
	}
	if len(got) != len(want) {
		t.Fatalf("requests edges = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("requests edges = %v, want %v", got, want)
		}
	}

	// Direct deps (via -r requirements.in) hang off the root.
	rootDeps := directDepIDs(t, g, findRootID(t, g))
	if !contains(rootDeps, "requests@2.21.0") || !contains(rootDeps, "django@1.11.29") {
		t.Errorf("root direct deps = %v, want requests + django", rootDeps)
	}
}

func TestRequirementsLockScopes(t *testing.T) {
	lockPath, dir := writeLock(t, sampleRequirementsLock)
	g, err := depGraphFromRequirementsLock(lockPath, dir)
	if err != nil {
		t.Fatalf("depGraphFromRequirementsLock: %v", err)
	}
	// pytest is dev-only (via requirements-dev.in).
	pytest, ok := g.Node("pytest@7.4.3")
	if !ok {
		t.Fatal("missing pytest node")
	}
	if pytest.PrimaryScope() != sdk.ScopeDevelopment {
		t.Errorf("pytest scope = %v, want development", pytest.PrimaryScope())
	}
	// urllib3 is reachable on a runtime path (requests) even though it is also
	// listed as a direct runtime dep — runtime must win.
	urllib3, ok := g.Node("urllib3@1.24.3")
	if !ok {
		t.Fatal("missing urllib3 node")
	}
	if urllib3.PrimaryScope() != sdk.ScopeRuntime {
		t.Errorf("urllib3 scope = %v, want runtime", urllib3.PrimaryScope())
	}
}

func TestParsePipLockMultilineVia(t *testing.T) {
	entries, err := parsePipLock([]byte(sampleRequirementsLock))
	if err != nil {
		t.Fatalf("parsePipLock: %v", err)
	}
	var urllib3 *pipLockEntry
	for _, e := range entries {
		if e.name == "urllib3" {
			urllib3 = e
		}
	}
	if urllib3 == nil {
		t.Fatal("urllib3 entry not parsed")
	}
	if !contains(urllib3.viaPkgs, "requests") {
		t.Errorf("urllib3 viaPkgs = %v, want requests", urllib3.viaPkgs)
	}
	if !contains(urllib3.viaFiles, "requirements.in") {
		t.Errorf("urllib3 viaFiles = %v, want requirements.in", urllib3.viaFiles)
	}
}

func TestPipLockFilePath(t *testing.T) {
	_, dir := writeLock(t, sampleRequirementsLock)
	if got := pipLockFilePath(dir); got == "" {
		t.Error("expected lock path, got empty")
	}
	if got := pipLockFilePath(t.TempDir()); got != "" {
		t.Errorf("expected empty path for dir without lock, got %q", got)
	}
}

func findRootID(t *testing.T, g *sdk.Graph) string {
	t.Helper()
	for _, n := range g.Nodes() {
		if n.Type == sdk.PackageTypeApplication {
			return n.ID
		}
	}
	t.Fatal("no application root node")
	return ""
}

func contains(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}
