package support

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bomly-dev/bomly-cli/internal/registry"
	"github.com/bomly-dev/bomly-cli/sdk"
	"go.uber.org/zap"
)

// proseFS holds optional hand-written prose appended to generated detector
// and matcher pages. The hybrid model: the structured fact table stays
// auto-generated; the surrounding prose is hand-edited and embedded via
// loadProse.
//
//go:embed all:prose
var proseFS embed.FS

// loadProse returns the Markdown contents of internal/support/prose/<kind>/<name>.md,
// or an empty string if no prose file exists.
func loadProse(kind, name string) string {
	data, err := proseFS.ReadFile(fmt.Sprintf("prose/%s/%s.md", kind, name))
	if err != nil {
		return ""
	}
	body := strings.TrimSpace(string(data))
	if body == "" {
		return ""
	}
	return body + "\n"
}

const generatedBanner = "<!-- The reference table below this banner is regenerated by `make generate`. Hand-written prose below the table lives in internal/support/prose/. -->"

// RenderDetectorsOverviewMarkdown renders the human-readable detector guide.
func RenderDetectorsOverviewMarkdown() string {
	return strings.TrimSpace(`# Detectors

Detectors turn a project, container, or SBOM into a dependency graph. Every scan starts with a detector.

A detector knows one or more package managers. Given evidence on disk — a lockfile, a manifest, a workflow file, an SBOM document — it produces packages, versions, and the edges between them. Bomly ships native detectors for the most common ecosystems and falls back to Syft for broad coverage of everything else.

## When detectors run

- `+"`bomly scan`"+` runs detectors to build the graph.
- `+"`bomly explain`"+` reuses the same detector planning before walking dependency paths.
- `+"`bomly diff`"+` runs detectors for each side of the comparison, unless you pass `+"`--sbom`"+` to diff two SBOM files directly.
- Plugin detectors participate in the same planning flow when they declare package-manager evidence.

## Detector Chains

A **detector chain** is the ordered list Bomly tries for a package manager. The first entry is preferred. Later entries are fallbacks Bomly uses when the preferred detector is not ready, is not applicable, or cannot produce graph data.

For example, the `+"`npm`"+` chain is `+"`npm-detector`"+` → `+"`syft-detector`"+`:

1. `+"`npm-detector`"+` parses `+"`package-lock.json`"+` directly and resolves the full transitive graph.
2. `+"`syft-detector`"+` runs only if the native detector cannot produce graph data (for example, no lockfile present), and emits a flat package list.

Per-ecosystem chains are listed in [`+"`detectors/ecosystems/`"+`](detectors/ecosystems/). The full live list lives in the CLI:

`+"```bash"+`
bomly plugin list --detectors
bomly plugin list --detectors --format json
`+"```"+`

## Native vs. Syft

| | Native detectors | Syft-backed |
| --- | --- | --- |
| Graph shape | Full transitive graph with edges | Flat package list |
| Source | Lockfile or build-tool output | Cataloger heuristics |
| Best for | Local source trees, monorepos, CI | Container images, ecosystems without a native detector |
| Performance | Faster on supported ecosystems | Required for many container layers |

Bomly prefers native detectors because they preserve edges (needed by `+"`bomly explain`"+`, reachability, and scope filtering). It falls back to Syft transparently when no native detector applies.

## Selecting detectors

Use `+"`--detectors`"+` to restrict or extend the default set with the standard `+"`+/-`"+` selector grammar:

`+"```bash"+`
# Use only the native Go detector
bomly scan --detectors go-detector

# Disable Syft fallback for this run
bomly scan --detectors -syft-detector

# Add an external plugin detector
bomly scan --detectors +acme.detector.example
`+"```"+`

Pass the bare detector name to filter to only that detector, `+"`+name`"+` to add it on top of defaults, or `+"`-name`"+` to remove it.

## Network behavior

Detectors differ in whether they run subprocesses, and those that do may invoke build tools that download packages from registries. The marketing claim "Bomly is offline-safe by default" is precise: **matchers** make zero outbound calls without `+"`--enrich`"+`. **Detectors** may invoke build tools that download packages on your behalf during normal graph resolution.

| Detector class | Examples | Network during normal scan |
| --- | --- | --- |
| Lockfile parser | `+"`npm-detector`"+`, `+"`pnpm-detector`"+`, `+"`bundler-detector`"+`, `+"`composer-detector`"+`, `+"`nuget-detector`"+`, `+"`github-actions-detector`"+`, SBOM ingest | None — pure file parse |
| Lockfile-first hybrid | `+"`cargo-detector`"+`, `+"`poetry-detector`"+`, `+"`uv-detector`"+` | None when the lockfile is present; the build-tool fallback uses `+"`--locked`"+` / `+"`--no-sync`"+` to stay offline |
| `+"`pip inspect`"+` | `+"`pip-detector`"+`, `+"`pipenv-detector`"+` | None — reads the local Python environment |
| Build-tool primary | `+"`go-detector`"+`, `+"`maven-detector`"+`, `+"`gradle-detector`"+`, `+"`sbt-native-detector`"+` | **May download** uncached artifacts during normal resolution |

The build-tool-primary detectors invoke commands you would already run locally (`+"`go list`"+`, `+"`mvn dependency:tree`"+`, `+"`gradle dependencies`"+`, `+"`sbt dependencyTree`"+`). Whether they hit the network is a property of those tools and your local cache state, not a Bomly choice. To keep these scans fully offline, pre-warm the local cache (`+"`go mod download`"+`, `+"`mvn dependency:go-offline`"+`, etc.) or commit a lockfile when the ecosystem supports one.

Per-PM pages under [`+"`detectors/ecosystems/`"+`](detectors/ecosystems/) document the exact command each detector runs and whether it touches the network.

## `+"`--install-first`"+` {#install-first}

Pass `+"`--install-first`"+` to let supporting detectors run their normal dependency-install command **before** resolving the graph. Today this is wired up only for the Node ecosystem (`+"`npm`"+`, `+"`pnpm`"+`, `+"`yarn`"+`); each runs the respective `+"`<pm> install`"+` command in the project directory.

⚠️ **`+"`--install-first`"+` downloads packages from the npm registry.** This is opt-in for a reason — it modifies the filesystem (writes to `+"`node_modules/`"+`) and can fetch many MB of dependencies. Use it when the lockfile is missing or stale and you want Bomly to refresh it on a clean checkout.

For other ecosystems, run the install command yourself before scanning (`+"`pip install -r requirements.txt`"+`, `+"`bundle install`"+`, `+"`composer install`"+`, `+"`poetry install`"+`, `+"`uv sync`"+`, etc.) and Bomly will read from the resulting lockfile or installed environment. Bomly does **not** install package managers themselves.

Each package-manager page under [`+"`detectors/ecosystems/`"+`](detectors/ecosystems/) lists whether `+"`--install-first`"+` is supported and the exact command that runs.

## Discovery and monorepos

For local source trees, Bomly discovers subprojects before running detectors. Every directory containing recognized evidence becomes a subproject; Bomly runs the matching detector chain in each one and consolidates the results into a single graph.

There is no project-root requirement. Pointing `+"`bomly scan`"+` at a monorepo will scan every workspace in one pass.

## SBOM ingest

Bomly treats SPDX 2.3 and CycloneDX SBOMs as first-class input. Use `+"`--sbom`"+` to ingest an SBOM file directly without re-running ecosystem detectors:

`+"```bash"+`
bomly scan --sbom --path ./existing.spdx.json
`+"```"+`

This is fast and offline. See [SBOM formats](SBOM.md) for the format comparison.

## Container images

Bomly resolves container references via the host's registry credentials. Native detectors that work on lockfile contents inside layers still run; everything else falls through to Syft:

`+"```bash"+`
bomly scan --container ghcr.io/example/app:latest
`+"```"+`

## See also

- [Ecosystem guides](detectors/ecosystems/) — generated per-ecosystem detector chains, evidence patterns, and `+"`PATH`"+` requirements
- [Support matrix](SUPPORT_MATRIX.md) — generated overview of every supported ecosystem
- [Plugins](PLUGINS.md) — author and install external detectors
`) + "\n"
}

// RenderMatchersOverviewMarkdown renders the human-readable matcher guide.
func RenderMatchersOverviewMarkdown() string {
	return strings.TrimSpace(`# Matchers

Matchers enrich packages after Bomly has built a dependency graph. They attach vulnerabilities, license metadata, and lifecycle signals to packages already in the graph.

Bomly is **offline-safe by default**. Matchers that use the network only run when you opt in with `+"`--enrich`"+`. A scan without `+"`--enrich`"+` makes zero outbound HTTP calls.

## Categories

| Kind | Examples | What it adds |
| --- | --- | --- |
| Vulnerability | `+"`osv`"+`, `+"`grype`"+` | CVE / GHSA / OSV IDs, severity, CVSS, aliases, fixed versions, references, KEV signal |
| License | `+"`depsdev-license-checker`"+`, `+"`clearlydefined-license-checker`"+` | SPDX expression, declared/discovered split, license source |
| Lifecycle | `+"`eol`"+` | End-of-life status for ecosystems and runtimes (via endoflife.date) |

The full live list lives in the CLI:

`+"```bash"+`
bomly plugin list --matchers
bomly plugin list --matchers --format json
`+"```"+`

## Running matchers

Pass `+"`--enrich`"+` to run all default network matchers:

`+"```bash"+`
bomly scan --enrich
`+"```"+`

Use `+"`--matchers`"+` to restrict or extend the set with the standard `+"`+/-`"+` selector grammar:

`+"```bash"+`
# Only OSV
bomly scan --enrich --matchers osv

# Default set minus license checkers
bomly scan --enrich --matchers -depsdev-license-checker,-clearlydefined-license-checker

# Add an external plugin matcher
bomly scan --enrich --matchers +acme.matcher.example
`+"```"+`

## Network endpoints

When `+"`--enrich`"+` is set, Bomly may call:

- `+"`api.osv.dev`"+` — OSV vulnerability database
- `+"`api.cisa.gov`"+` — CISA Known Exploited Vulnerabilities catalog
- `+"`api.deps.dev`"+` — Google's deps.dev package metadata
- `+"`api.clearlydefined.io`"+` — ClearlyDefined license data
- `+"`endoflife.date`"+` — lifecycle data

These are the **only** hosts Bomly contacts during enrichment. No telemetry. No data exfiltration. No credentials sent. See [docs/ARCHITECTURE.md](ARCHITECTURE.md) for the full network model.

## Cache

Every matcher caches its responses on disk so repeated scans are fast and resilient to upstream outages.

| | Default |
| --- | --- |
| Cache root (Unix/macOS) | `+"`$HOME/.bomly/cache/`"+` |
| Cache root (Windows) | `+"`%USERPROFILE%\\.bomly\\cache\\`"+` |
| Fallback when no home dir | `+"`./.bomly-cache/`"+` |

Per-matcher subdirectories and TTLs:

| Matcher | Subdirectory | Default TTL |
| --- | --- | --- |
| OSV (queries) | `+"`osv/`"+` | 24h |
| OSV (vulnerability details) | `+"`osv-vulns/`"+` | 7d |
| CISA KEV | `+"`kev/`"+` | 6h |
| deps.dev | `+"`licenses/depsdev/`"+` | 24h |
| ClearlyDefined | `+"`licenses/clearlydefined/`"+` | 24h |
| endoflife.date | `+"`eol/`"+` | 24h |

To clear the cache, delete the directory:

`+"```bash"+`
rm -rf ~/.bomly/cache    # Unix/macOS
Remove-Item -Recurse $env:USERPROFILE\.bomly\cache  # PowerShell
`+"```"+`

Override the cache location per matcher in `+"`~/.bomly/config.yaml`"+`; see [CONFIG_REFERENCE.md](CONFIG_REFERENCE.md). Cache failures are **always non-fatal** — Bomly logs a warning and continues.

## Failure semantics

Matchers degrade rather than abort. A failed enrichment never fails the scan:

- **Network error** — the package is left unannotated; a warning is logged.
- **Cache write error** — the response is still applied; a warning is logged.
- **Rate-limit / 5xx** — Bomly retries with backoff inside the matcher, then degrades.

This means a scan with `+"`--enrich`"+` always succeeds (exit 0) on a healthy graph, even if some enrichment lookups failed. To enforce that enrichment data must be present, combine `+"`--enrich`"+` with `+"`--audit --fail-on <severity>`"+` — see [Auditors](AUDITORS.md).

## See also

- [Per-matcher reference](matchers/) — descriptors, cache shape, output fields, ecosystem coverage
- [Auditors](AUDITORS.md) — how matcher output is evaluated against policy
- [Reachability](REACHABILITY.md) — narrowing matcher findings to symbols actually called
`) + "\n"
}

// RenderAuditorsOverviewMarkdown renders the human-readable auditor guide.
func RenderAuditorsOverviewMarkdown() string {
	return strings.TrimSpace(`# Auditors

Auditors evaluate a dependency graph against policy and produce findings. They are how a scan becomes a pass/fail signal in CI.

Auditors run **after** detectors and matchers. They never make network calls of their own — they only look at the data that detectors put on the graph and matchers attached to it. To audit fresh vulnerability data, combine `+"`--enrich`"+` with `+"`--audit`"+`:

`+"```bash"+`
bomly scan --enrich --audit --fail-on high
`+"```"+`

`+"`--audit`"+` alone is useful when you have ingested an SBOM that already carries vulnerability data, or when a matcher ran in a previous step.

## When auditors run

- `+"`bomly scan --audit`"+` evaluates the full graph.
- `+"`bomly explain --audit`"+` evaluates the dependency-path context for a single package.
- `+"`bomly diff --audit`"+` classifies introduced, resolved, and persisted findings between two graphs.

## Findings

A finding is Bomly's normalized record of a policy match. Every finding has:

| Field | Meaning |
| --- | --- |
| ID | Identifier of the underlying signal (e.g. `+"`CVE-2024-12345`"+`, `+"`GHSA-xxxx-yyyy-zzzz`"+`) |
| Kind | What kind of finding (vulnerability, license, lifecycle) |
| Severity | `+"`critical`"+` / `+"`high`"+` / `+"`medium`"+` / `+"`low`"+` / `+"`unknown`"+` |
| Package | The package name, version, and PURL it applies to |
| Title | Human-readable summary |
| Reasons | Why the finding matched policy (e.g. severity threshold, reachable symbol) |
| Source | Which matcher produced the underlying data |

Text output (`+"`--format text`"+`, default) groups findings by package and severity. JSON (`+"`--format json`"+`) exposes the full shape for automation. SARIF 2.1.0 (`+"`--format sarif`"+`) emits a static-analysis report any tool that consumes SARIF can ingest.

`+"`--format sarif`"+` **requires** `+"`--audit`"+`. A SARIF document only makes sense when there are findings.

## Severity grammar

Severity levels in precedence order, lowest to highest:

`+"```text"+`
unknown  <  low  <  medium  <  high  <  critical
`+"```"+`

The `+"`any`"+` token matches every severity, including `+"`unknown`"+`.

## `+"`--fail-on`"+`

`+"`--fail-on`"+` is the only knob that turns a finding into a non-zero exit code. It accepts one of the severity tokens, or the reachability token `+"`reachable`"+`:

| Token | Matches |
| --- | --- |
| `+"`any`"+` | every finding |
| `+"`low`"+` | findings with severity ≥ low |
| `+"`medium`"+` | findings with severity ≥ medium |
| `+"`high`"+` | findings with severity ≥ high |
| `+"`critical`"+` | findings with severity = critical |
| `+"`reachable`"+` | findings where reachability status is `+"`reachable`"+` (experimental — see [REACHABILITY.md](REACHABILITY.md)) |

Repeat the flag to AND constraints together:

`+"```bash"+`
# Fail on any high or critical finding
bomly scan --enrich --audit --fail-on high

# Fail only when a high-or-above finding is also reachable
bomly scan --enrich --audit --reachability \
  --fail-on high --fail-on reachable
`+"```"+`

Tokens are case-insensitive. An invalid token produces an exit-code 4 (invalid input) with the message:
`+"`unsupported --fail-on value \"<x>\" (accepted: any, low, medium, high, critical, reachable)`"+`.

## `+"`--fail-on-scope`"+`

Use `+"`--fail-on-scope`"+` to restrict which dependency scopes feed into `+"`--fail-on`"+`:

| Scope | Meaning |
| --- | --- |
| `+"`runtime`"+` | Required at runtime (e.g. `+"`dependencies`"+` in npm, non-test scope in Maven) |
| `+"`development`"+` | Build- and test-only (e.g. `+"`devDependencies`"+` in npm, `+"`test`"+` scope in Maven) |
| `+"`unknown`"+` | Detector could not classify the edge |

Without `+"`--fail-on-scope`"+` all scopes count. Common pattern: gate CI on runtime only.

`+"```bash"+`
bomly scan --enrich --audit --fail-on high --fail-on-scope runtime
`+"```"+`

## Exit codes from auditors

| Code | Trigger |
| --- | --- |
| 0 | Scan succeeded; no policy match for `+"`--fail-on`"+` |
| 2 | Policy violation — at least one finding matched `+"`--fail-on`"+` |
| 4 | Invalid `+"`--fail-on`"+` or `+"`--fail-on-scope`"+` value |

See [EXIT_CODES.md](EXIT_CODES.md) for the full table.

## Diff and auditing

`+"`bomly diff --audit`"+` classifies findings between two graphs into three buckets:

- **Introduced** — present in head, absent in base
- **Resolved** — present in base, absent in head
- **Persisted** — present in both

Combine with `+"`--fail-on`"+` to fail PRs that introduce new high-severity findings without complaining about pre-existing ones:

`+"```bash"+`
bomly diff --base main --head HEAD --enrich --audit --fail-on high
`+"```"+`

## See also

- [Exit codes](EXIT_CODES.md) — full table of process exit values
- [Reachability](REACHABILITY.md) — narrowing findings to symbols actually called
- [Output formats](OUTPUT_FORMATS.md) — text, JSON, SARIF rendering details
- [Matchers](MATCHERS.md) — where finding data comes from
`) + "\n"
}

// WriteComponentDocs writes generated detector and matcher documentation.
func WriteComponentDocs(docsDir string) error {
	files := map[string]string{
		filepath.Join(docsDir, "DETECTORS.md"): RenderDetectorsOverviewMarkdown(),
		filepath.Join(docsDir, "MATCHERS.md"):  RenderMatchersOverviewMarkdown(),
		filepath.Join(docsDir, "AUDITORS.md"):  RenderAuditorsOverviewMarkdown(),
	}
	for path, content := range files {
		if err := writeMarkdown(path, content); err != nil {
			return err
		}
	}
	if err := writeDetectorEcosystemDocs(filepath.Join(docsDir, "detectors", "ecosystems")); err != nil {
		return err
	}
	if err := writeMatcherDocs(filepath.Join(docsDir, "matchers")); err != nil {
		return err
	}
	return nil
}

func writeDetectorEcosystemDocs(outputDir string) error {
	// Wipe and recreate the output directory so renamed or removed ecosystems
	// and package managers don't leave orphan files behind.
	if err := os.RemoveAll(outputDir); err != nil {
		return fmt.Errorf("clean %s: %w", outputDir, err)
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", outputDir, err)
	}
	entries := registry.SupportEntries()
	byEcosystem := make(map[sdk.Ecosystem][]registry.PackageManagerSupport)
	for _, entry := range entries {
		byEcosystem[entry.Ecosystem] = append(byEcosystem[entry.Ecosystem], entry)
	}
	ecosystems := make([]sdk.Ecosystem, 0, len(byEcosystem))
	for ecosystem := range byEcosystem {
		ecosystems = append(ecosystems, ecosystem)
	}
	sort.Slice(ecosystems, func(i, j int) bool { return ecosystems[i] < ecosystems[j] })
	for _, ecosystem := range ecosystems {
		ecosystemDir := filepath.Join(outputDir, string(ecosystem))
		if err := os.MkdirAll(ecosystemDir, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", ecosystemDir, err)
		}
		ecosystemEntries := byEcosystem[ecosystem]
		sort.Slice(ecosystemEntries, func(i, j int) bool {
			return ecosystemEntries[i].Manager.Name() < ecosystemEntries[j].Manager.Name()
		})
		for _, entry := range ecosystemEntries {
			path := filepath.Join(ecosystemDir, entry.Manager.Name()+".md")
			if err := writeMarkdown(path, renderPackageManagerMarkdown(ecosystem, entry)); err != nil {
				return err
			}
		}
		if err := writeMarkdown(filepath.Join(ecosystemDir, "README.md"), renderEcosystemReadme(ecosystem, ecosystemEntries)); err != nil {
			return err
		}
	}
	return writeMarkdown(filepath.Join(outputDir, "README.md"), renderDetectorEcosystemIndex(ecosystems, byEcosystem))
}

func renderDetectorEcosystemIndex(ecosystems []sdk.Ecosystem, byEcosystem map[sdk.Ecosystem][]registry.PackageManagerSupport) string {
	var b strings.Builder
	b.WriteString("# Detector Ecosystem Guides\n\n")
	b.WriteString(generatedBanner + "\n\n")
	b.WriteString("Bomly groups detectors by **ecosystem** (the package universe — `go`, `npm`, `python`, `maven`, …) and writes one page per **package manager** within that ecosystem (`pip`, `poetry`, `uv` are all under `python`).\n\n")
	b.WriteString("Pick your ecosystem to see the package managers it covers and how each one is detected.\n\n")
	b.WriteString("| Ecosystem | Package managers |\n")
	b.WriteString("| --- | --- |\n")
	for _, ecosystem := range ecosystems {
		entries := byEcosystem[ecosystem]
		links := make([]string, 0, len(entries))
		for _, entry := range entries {
			name := entry.Manager.Name()
			links = append(links, fmt.Sprintf("[`%s`](%s/%s.md)", name, ecosystem, name))
		}
		fmt.Fprintf(&b, "| [%s](%s/) | %s |\n", ecosystem, ecosystem, strings.Join(links, ", "))
	}
	return b.String()
}

func renderEcosystemReadme(ecosystem sdk.Ecosystem, entries []registry.PackageManagerSupport) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", titleWords(string(ecosystem)))
	b.WriteString(generatedBanner + "\n\n")
	fmt.Fprintf(&b, "Package managers Bomly recognizes in the `%s` ecosystem:\n\n", ecosystem)
	b.WriteString("| Package manager | Detector chain | Evidence patterns | Install-first support |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, entry := range entries {
		name := entry.Manager.Name()
		fmt.Fprintf(&b, "| [`%s`](%s.md) | %s | %s | %s |\n",
			name,
			name,
			codeList(entry.Detectors),
			codeListOrDash(entry.EvidencePatterns),
			yesNo(chainSupportsInstallFirst(entry.Detectors)),
		)
	}
	b.WriteString("\n## How to read this\n\n")
	b.WriteString("- Each package-manager page documents the exact commands Bomly runs (if any), the network behavior, and the lockfile or manifest formats supported.\n")
	b.WriteString("- Bomly tries detector chains from left to right. Later detectors in the chain are fallbacks Bomly uses when the preferred detector cannot produce graph data.\n")
	b.WriteString("- Install-first support means `--install-first` can run the package manager's normal install command before graph resolution. This downloads packages and modifies the filesystem; see [docs/DETECTORS.md](../../DETECTORS.md#install-first).\n")
	b.WriteString("- Syft-backed entries provide broad compatibility, especially for containers and ecosystems without native Bomly graph resolution.\n")
	return b.String()
}

func renderPackageManagerMarkdown(ecosystem sdk.Ecosystem, entry registry.PackageManagerSupport) string {
	name := entry.Manager.Name()
	var b strings.Builder
	fmt.Fprintf(&b, "# `%s` (%s ecosystem)\n\n", name, ecosystem)
	b.WriteString(generatedBanner + "\n\n")
	fmt.Fprintf(&b, "Bomly uses this chain when it finds `%s` evidence.\n\n", name)
	b.WriteString("| Property | Value |\n")
	b.WriteString("| --- | --- |\n")
	fmt.Fprintf(&b, "| Package manager | `%s` |\n", name)
	fmt.Fprintf(&b, "| Ecosystem | `%s` |\n", ecosystem)
	fmt.Fprintf(&b, "| Detector chain | %s |\n", codeList(entry.Detectors))
	fmt.Fprintf(&b, "| Evidence patterns | %s |\n", codeListOrDash(entry.EvidencePatterns))
	fmt.Fprintf(&b, "| Install-first support | %s |\n", yesNo(chainSupportsInstallFirst(entry.Detectors)))
	fmt.Fprintf(&b, "| Native command hints | %s |\n", commandHintsForChain(entry.Detectors))
	if prose := loadProse("detectors", name); prose != "" {
		b.WriteString("\n")
		b.WriteString(prose)
	}
	return b.String()
}

func writeMatcherDocs(outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", outputDir, err)
	}
	reg := registry.NewRegistry(registry.RegistryConfigs{}, *zap.NewNop())
	reg.Build()
	descriptors := reg.MatcherDescriptors()
	sort.Slice(descriptors, func(i, j int) bool { return descriptors[i].Name < descriptors[j].Name })
	for _, descriptor := range descriptors {
		if err := writeMarkdown(filepath.Join(outputDir, descriptor.Name+".md"), renderMatcherMarkdown(descriptor)); err != nil {
			return err
		}
	}
	return writeMarkdown(filepath.Join(outputDir, "README.md"), renderMatcherIndex(descriptors))
}

func renderMatcherIndex(descriptors []sdk.MatcherDescriptor) string {
	var b strings.Builder
	b.WriteString("# Matcher Guides\n\n")
	b.WriteString("These generated pages explain Bomly's built-in enrichment matchers.\n\n")
	for _, descriptor := range descriptors {
		fmt.Fprintf(&b, "- [%s](%s.md)\n", humanMatcherTitle(descriptor.Name), descriptor.Name)
	}
	return b.String()
}

func renderMatcherMarkdown(descriptor sdk.MatcherDescriptor) string {
	behavior := matcherBehavior(descriptor.Name)
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", humanMatcherTitle(descriptor.Name))
	b.WriteString(generatedBanner + "\n\n")
	fmt.Fprintf(&b, "%s\n\n", behavior.Summary)
	b.WriteString("| Property | Value |\n")
	b.WriteString("| --- | --- |\n")
	fmt.Fprintf(&b, "| Matcher name | `%s` |\n", descriptor.Name)
	fmt.Fprintf(&b, "| Runs by default | %s |\n", yesNo(descriptor.Enabled && !behavior.RequiresEnrich))
	fmt.Fprintf(&b, "| Requires enrichment | %s |\n", yesNo(behavior.RequiresEnrich))
	fmt.Fprintf(&b, "| Uses network | %s |\n", yesNo(behavior.UsesNetwork))
	fmt.Fprintf(&b, "| Cache behavior | %s |\n", behavior.Cache)
	fmt.Fprintf(&b, "| Output fields | %s |\n", strings.Join(behavior.OutputFields, ", "))
	if len(descriptor.Capabilities) > 0 {
		fmt.Fprintf(&b, "| Capabilities | %s |\n", codeList(descriptor.Capabilities))
	}
	if len(descriptor.SupportedEcosystems) > 0 {
		fmt.Fprintf(&b, "| Ecosystems | %s |\n", ecosystemCodeList(descriptor.SupportedEcosystems))
	}
	b.WriteString("\n## User notes\n\n")
	b.WriteString(behavior.Notes)
	b.WriteString("\n")
	if prose := loadProse("matchers", descriptor.Name); prose != "" {
		b.WriteString("\n")
		b.WriteString(prose)
	}
	return b.String()
}

type matcherDocBehavior struct {
	Summary        string
	RequiresEnrich bool
	UsesNetwork    bool
	Cache          string
	OutputFields   []string
	Notes          string
}

func matcherBehavior(name string) matcherDocBehavior {
	switch name {
	case "osv":
		return matcherDocBehavior{
			Summary:        "Looks up package vulnerabilities in OSV and annotates matching packages.",
			RequiresEnrich: true,
			UsesNetwork:    true,
			Cache:          "Uses Bomly's matcher cache; cache failures are warnings, not scan failures.",
			OutputFields:   []string{"vulnerability ID", "severity", "aliases", "CVSS", "fixed version", "references", "KEV signal"},
			Notes:          "Run with `--enrich` to query OSV. Combine `--enrich --audit` when you want OSV data evaluated by policy in the same run.",
		}
	case "grype":
		return matcherDocBehavior{
			Summary:        "Uses Grype vulnerability matching against the resolved dependency graph.",
			RequiresEnrich: true,
			UsesNetwork:    false,
			Cache:          "Relies on Grype's local vulnerability database behavior.",
			OutputFields:   []string{"vulnerability ID", "severity", "CVSS", "fixed version", "references"},
			Notes:          "The full Bomly binary links Grype support. The lite binary uses an external `grype` executable on `PATH`.",
		}
	case "depsdev-license-checker":
		return matcherDocBehavior{
			Summary:        "Fetches package metadata from deps.dev to improve license coverage.",
			RequiresEnrich: true,
			UsesNetwork:    true,
			Cache:          "Uses Bomly's matcher cache; cache failures are non-fatal.",
			OutputFields:   []string{"license value", "license source", "matched package flag"},
			Notes:          "Run with `--enrich` when you want license metadata from deps.dev.",
		}
	case "clearlydefined-license-checker":
		return matcherDocBehavior{
			Summary:        "Fetches license metadata from ClearlyDefined.",
			RequiresEnrich: true,
			UsesNetwork:    true,
			Cache:          "Uses Bomly's matcher cache; cache failures are non-fatal.",
			OutputFields:   []string{"license value", "license source", "matched package flag"},
			Notes:          "Run with `--enrich` when you want ClearlyDefined license evidence.",
		}
	case "eol":
		return matcherDocBehavior{
			Summary:        "Checks endoflife.date for lifecycle metadata where Bomly can map a package or platform.",
			RequiresEnrich: true,
			UsesNetwork:    true,
			Cache:          "Uses Bomly's matcher cache; cache failures are non-fatal.",
			OutputFields:   []string{"metadata.eol", "matched package flag"},
			Notes:          "Run with `--enrich` to attach lifecycle metadata. Audit behavior depends on auditor policy support for that metadata.",
		}
	default:
		return matcherDocBehavior{
			Summary:        "Enriches Bomly package data.",
			RequiresEnrich: true,
			UsesNetwork:    false,
			Cache:          "Matcher-specific.",
			OutputFields:   []string{"matcher-specific package metadata"},
			Notes:          "Run with `--enrich` when this matcher should participate in scans.",
		}
	}
}

func chainSupportsInstallFirst(detectors []string) bool {
	for _, detectorName := range detectors {
		if detectorSupportsInstallFirst(detectorName) {
			return true
		}
	}
	return false
}

func detectorSupportsInstallFirst(detectorName string) bool {
	reg := registry.NewRegistry(registry.RegistryConfigs{}, *zap.NewNop())
	reg.Build()
	for _, descriptor := range reg.DetectorDescriptors() {
		if descriptor.Name == detectorName {
			return descriptor.SupportsInstallFirst
		}
	}
	return false
}

func commandHintsForChain(detectors []string) string {
	seen := make(map[string]struct{})
	values := make([]string, 0)
	for _, detector := range detectors {
		for _, command := range commandHintsForDetector(detector) {
			if _, ok := seen[command]; ok {
				continue
			}
			seen[command] = struct{}{}
			values = append(values, command)
		}
	}
	if len(values) == 0 {
		return "-"
	}
	return codeList(values)
}

func commandHintsForDetector(detector string) []string {
	switch {
	case strings.Contains(detector, "npm"):
		return []string{"npm"}
	case strings.Contains(detector, "pnpm"):
		return []string{"pnpm"}
	case strings.Contains(detector, "yarn"):
		return []string{"yarn"}
	case detector == "go-detector" || strings.Contains(detector, "gomod"):
		return []string{"go"}
	case strings.Contains(detector, "maven"):
		return []string{"mvn"}
	case strings.Contains(detector, "gradle"):
		return []string{"gradle"}
	case strings.Contains(detector, "composer"):
		return []string{"composer"}
	case strings.Contains(detector, "bundler") || strings.Contains(detector, "ruby"):
		return []string{"bundle"}
	case strings.Contains(detector, "pipenv"):
		return []string{"pipenv"}
	case strings.Contains(detector, "poetry"):
		return []string{"poetry"}
	case strings.Contains(detector, "uv"):
		return []string{"uv"}
	case strings.Contains(detector, "pip"):
		return []string{"pip"}
	case strings.Contains(detector, "cargo"):
		return []string{"cargo"}
	case strings.Contains(detector, "nuget"):
		return []string{"dotnet"}
	case strings.Contains(detector, "mix"):
		return []string{"mix"}
	case strings.Contains(detector, "conan"):
		return []string{"conan"}
	case strings.Contains(detector, "pub"):
		return []string{"dart"}
	case strings.Contains(detector, "swiftpm"):
		return []string{"swift"}
	case strings.Contains(detector, "sbt"):
		return []string{"sbt"}
	case strings.Contains(detector, "syft"):
		return []string{"syft for bomly-lite"}
	default:
		return nil
	}
}

func ecosystemCodeList(values []sdk.Ecosystem) string {
	items := make([]string, 0, len(values))
	for _, value := range values {
		items = append(items, string(value))
	}
	return codeList(items)
}

func humanMatcherTitle(name string) string {
	switch name {
	case "osv":
		return "OSV"
	case "grype":
		return "Grype"
	case "depsdev-license-checker":
		return "deps.dev License Checker"
	case "clearlydefined-license-checker":
		return "ClearlyDefined License Checker"
	case "eol":
		return "endoflife.date"
	default:
		return titleWords(strings.ReplaceAll(name, "-", " "))
	}
}

func titleWords(value string) string {
	parts := strings.Fields(strings.ReplaceAll(value, "-", " "))
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}

func yesNo(value bool) string {
	if value {
		return "Yes"
	}
	return "No"
}

func writeMarkdown(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(path), err)
	}
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
