package support

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/bomly-dev/bomly-cli/internal/config"
)

type configField struct {
	Name       string
	YAMLKey    string
	EnvVar     string
	Doc        string
	DefaultVal string
	GoType     string
	Section    string
}

// GenerateConfigReference renders the config reference markdown from the given config source file.
func GenerateConfigReference(configPath string) (string, int, error) {
	fields, err := parseConfigFields(configPath)
	if err != nil {
		return "", 0, err
	}
	return renderConfigMarkdown(fields), len(fields), nil
}

// WriteConfigReference writes the generated config reference markdown to disk.
func WriteConfigReference(configPath, outputPath string) (int, error) {
	markdown, fieldCount, err := GenerateConfigReference(configPath)
	if err != nil {
		return 0, err
	}
	if err := os.WriteFile(outputPath, []byte(markdown), 0o644); err != nil {
		return 0, fmt.Errorf("write %s: %w", outputPath, err)
	}
	return fieldCount, nil
}

func parseConfigFields(configPath string) ([]configField, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, configPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", configPath, err)
	}

	fileConfigYAML := config.YAMLPathsByResolvedField()

	var fields []configField
	currentSection := "General"

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "Resolved" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				if field.Doc != nil {
					for _, comment := range field.Doc.List {
						text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
						if text != "" && !strings.Contains(text, "`") {
							currentSection = text
						}
					}
				}
				if field.Comment != nil {
					for _, comment := range field.Comment.List {
						text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
						if text != "" {
							currentSection = text
						}
					}
				}

				if len(field.Names) == 0 {
					continue
				}

				name := field.Names[0].Name
				goType := configTypeString(field.Type)
				tag := ""
				if field.Tag != nil {
					tag = strings.Trim(field.Tag.Value, "`")
				}

				structTag := reflect.StructTag(tag)
				envVar := structTag.Get("env")
				doc := structTag.Get("doc")
				defaultVal := structTag.Get("default")

				if doc == "" {
					continue
				}

				yamlKey := fileConfigYAML[name]
				if yamlKey == "" {
					continue
				}

				fields = append(fields, configField{
					Name:       name,
					YAMLKey:    yamlKey,
					EnvVar:     envVar,
					Doc:        doc,
					DefaultVal: defaultVal,
					GoType:     goType,
					Section:    currentSection,
				})
			}
		}
	}
	return fields, nil
}

func renderConfigMarkdown(fields []configField) string {
	var builder strings.Builder
	builder.WriteString("# Configuration Reference\n\n")
	builder.WriteString("<!-- Auto-generated by go generate. Do not edit manually. -->\n\n")
	builder.WriteString("Bomly resolves configuration in the following order, with later sources overriding earlier ones:\n\n")
	builder.WriteString("1. `~/.bomly/config.yaml`\n")
	builder.WriteString("2. `<project>/.bomly/config.yaml`\n")
	builder.WriteString("3. `BOMLY_*` environment variables\n")
	builder.WriteString("4. CLI flags\n\n")
	builder.WriteString("`--config <path>` adds an explicit config file to the load list before environment variables and flags are applied.\n\n")
	builder.WriteString("YAML files use the nested keys documented below. Unknown keys and the former flat keys are rejected so configuration mistakes fail fast.\n\n")
	builder.WriteString("---\n\n")

	type sectionGroup struct {
		name   string
		fields []configField
	}

	var sections []sectionGroup
	sectionIdx := map[string]int{}
	for _, field := range fields {
		idx, ok := sectionIdx[field.Section]
		if !ok {
			idx = len(sections)
			sectionIdx[field.Section] = idx
			sections = append(sections, sectionGroup{name: field.Section})
		}
		sections[idx].fields = append(sections[idx].fields, field)
	}

	for _, section := range sections {
		builder.WriteString("## " + section.name + "\n\n")
		builder.WriteString("| YAML Key | Environment Variable | Type | Default | Description |\n")
		builder.WriteString("|----------|---------------------|------|---------|-------------|\n")
		for _, field := range section.fields {
			defaultVal := field.DefaultVal
			if defaultVal == "" {
				defaultVal = "-"
			}
			envVar := field.EnvVar
			if envVar == "" {
				envVar = "-"
			}
			fmt.Fprintf(&builder, "| `%s` | `%s` | `%s` | %s | %s |\n", field.YAMLKey, envVar, field.GoType, defaultVal, field.Doc)
		}
		builder.WriteString("\n")
	}

	builder.WriteString("## Flat YAML Migration\n\n")
	builder.WriteString("Flat YAML keys are no longer accepted. Move each existing key to its nested replacement:\n\n")
	builder.WriteString("| Former Flat Key | Replacement |\n")
	builder.WriteString("|-----------------|-------------|\n")
	migrations := config.LegacyMigrationPaths()
	legacyKeys := make([]string, 0, len(migrations))
	for key := range migrations {
		legacyKeys = append(legacyKeys, key)
	}
	sort.Strings(legacyKeys)
	for _, key := range legacyKeys {
		fmt.Fprintf(&builder, "| `%s` | `%s` |\n", key, migrations[key])
	}
	builder.WriteString("\n")

	builder.WriteString("## Example Configuration\n\n")
	builder.WriteString("```yaml\n")
	builder.WriteString("# ~/.bomly/config.yaml or .bomly/config.yaml\n")
	writeNestedConfigExample(&builder, fields)
	builder.WriteString("```\n")

	return builder.String()
}

func writeNestedConfigExample(builder *strings.Builder, fields []configField) {
	fieldsByPath := make(map[string]configField, len(fields))
	for _, field := range fields {
		fieldsByPath[field.YAMLKey] = field
	}
	writeNestedConfigType(builder, reflect.TypeOf(config.File{}), "", 0, fieldsByPath)
}

func writeNestedConfigType(builder *strings.Builder, t reflect.Type, prefix string, depth int, fields map[string]configField) {
	for idx := 0; idx < t.NumField(); idx++ {
		structField := t.Field(idx)
		key := yamlTagName(structField.Tag.Get("yaml"))
		if key == "" || key == "-" {
			continue
		}
		path := key
		if prefix != "" {
			path = prefix + "." + key
		}
		if structField.Type.Kind() == reflect.Struct {
			if !hasConfigPath(fields, path+".") {
				continue
			}
			fmt.Fprintf(builder, "# %s%s:\n", strings.Repeat("  ", depth), key)
			writeNestedConfigType(builder, structField.Type, path, depth+1, fields)
			continue
		}
		field, ok := fields[path]
		if !ok {
			continue
		}
		indent := strings.Repeat("  ", depth)
		fmt.Fprintf(builder, "# %s%s\n", indent, field.Doc)
		fmt.Fprintf(builder, "# %s%s: %s\n", indent, key, exampleConfigValue(field))
	}
}

func hasConfigPath(fields map[string]configField, prefix string) bool {
	for path := range fields {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}
	return false
}

func exampleConfigValue(field configField) string {
	if field.DefaultVal != "" {
		return field.DefaultVal
	}
	switch field.GoType {
	case "bool":
		return "false"
	case "int":
		return "0"
	case "string":
		return "\"\""
	case "[]string":
		return "[]"
	case "map[string]any", "map[string]map[string]any":
		return "{}"
	default:
		return "\"\""
	}
}

func yamlTagName(tag string) string {
	if idx := strings.Index(tag, ","); idx >= 0 {
		tag = tag[:idx]
	}
	return tag
}

func configTypeString(expr ast.Expr) string {
	switch typed := expr.(type) {
	case *ast.Ident:
		return typed.Name
	case *ast.ArrayType:
		return "[]" + configTypeString(typed.Elt)
	case *ast.MapType:
		return "map[" + configTypeString(typed.Key) + "]" + configTypeString(typed.Value)
	case *ast.StarExpr:
		return "*" + configTypeString(typed.X)
	case *ast.SelectorExpr:
		return configTypeString(typed.X) + "." + typed.Sel.Name
	default:
		return "any"
	}
}
