package support

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"strings"
)

type configField struct {
	Name       string
	YAMLKey    string
	EnvVar     string
	Doc        string
	DefaultVal string
	GoType     string
	Section    string
}

// GenerateConfigReference renders the config reference markdown from the given config source file.
func GenerateConfigReference(configPath string) (string, int, error) {
	fields, err := parseConfigFields(configPath)
	if err != nil {
		return "", 0, err
	}
	return renderConfigMarkdown(fields), len(fields), nil
}

// WriteConfigReference writes the generated config reference markdown to disk.
func WriteConfigReference(configPath, outputPath string) (int, error) {
	markdown, fieldCount, err := GenerateConfigReference(configPath)
	if err != nil {
		return 0, err
	}
	if err := os.WriteFile(outputPath, []byte(markdown), 0o644); err != nil {
		return 0, fmt.Errorf("write %s: %w", outputPath, err)
	}
	return fieldCount, nil
}

func parseConfigFields(configPath string) ([]configField, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, configPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", configPath, err)
	}

	fileConfigYAML := map[string]string{}
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "fileConfig" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				if len(field.Names) == 0 || field.Tag == nil {
					continue
				}
				tag := strings.Trim(field.Tag.Value, "`")
				structTag := reflect.StructTag(tag)
				yamlKey := structTag.Get("yaml")
				if i := strings.Index(yamlKey, ","); i >= 0 {
					yamlKey = yamlKey[:i]
				}
				if yamlKey != "" && yamlKey != "-" {
					fileConfigYAML[field.Names[0].Name] = yamlKey
				}
			}
		}
	}

	var fields []configField
	currentSection := "General"

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "resolvedConfig" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				if field.Doc != nil {
					for _, comment := range field.Doc.List {
						text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
						if text != "" && !strings.Contains(text, "`") {
							currentSection = text
						}
					}
				}
				if field.Comment != nil {
					for _, comment := range field.Comment.List {
						text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
						if text != "" {
							currentSection = text
						}
					}
				}

				if len(field.Names) == 0 {
					continue
				}

				name := field.Names[0].Name
				goType := configTypeString(field.Type)
				tag := ""
				if field.Tag != nil {
					tag = strings.Trim(field.Tag.Value, "`")
				}

				structTag := reflect.StructTag(tag)
				envVar := structTag.Get("env")
				doc := structTag.Get("doc")
				defaultVal := structTag.Get("default")

				if doc == "" {
					continue
				}

				yamlKey := fileConfigYAML[name]
				if yamlKey == "" {
					yamlKey = toSnakeCase(name)
				}

				fields = append(fields, configField{
					Name:       name,
					YAMLKey:    yamlKey,
					EnvVar:     envVar,
					Doc:        doc,
					DefaultVal: defaultVal,
					GoType:     goType,
					Section:    currentSection,
				})
			}
		}
	}
	return fields, nil
}

func renderConfigMarkdown(fields []configField) string {
	var builder strings.Builder
	builder.WriteString("# Configuration Reference\n\n")
	builder.WriteString("<!-- Auto-generated by go generate. Do not edit manually. -->\n\n")
	builder.WriteString("Bomly resolves configuration in the following order, with later sources overriding earlier ones:\n\n")
	builder.WriteString("1. `~/.bomly/config.yaml`\n")
	builder.WriteString("2. `<project>/.bomly/config.yaml`\n")
	builder.WriteString("3. `BOMLY_*` environment variables\n")
	builder.WriteString("4. CLI flags\n\n")
	builder.WriteString("`--config <path>` adds an explicit config file to the load list before environment variables and flags are applied.\n\n")
	builder.WriteString("---\n\n")

	type sectionGroup struct {
		name   string
		fields []configField
	}

	var sections []sectionGroup
	sectionIdx := map[string]int{}
	for _, field := range fields {
		idx, ok := sectionIdx[field.Section]
		if !ok {
			idx = len(sections)
			sectionIdx[field.Section] = idx
			sections = append(sections, sectionGroup{name: field.Section})
		}
		sections[idx].fields = append(sections[idx].fields, field)
	}

	for _, section := range sections {
		builder.WriteString("## " + section.name + "\n\n")
		builder.WriteString("| YAML Key | Environment Variable | Type | Default | Description |\n")
		builder.WriteString("|----------|---------------------|------|---------|-------------|\n")
		for _, field := range section.fields {
			defaultVal := field.DefaultVal
			if defaultVal == "" {
				defaultVal = "-"
			}
			envVar := field.EnvVar
			if envVar == "" {
				envVar = "-"
			}
			builder.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | %s | %s |\n", field.YAMLKey, envVar, field.GoType, defaultVal, field.Doc))
		}
		builder.WriteString("\n")
	}

	builder.WriteString("## Example Configuration\n\n")
	builder.WriteString("```yaml\n")
	builder.WriteString("# ~/.bomly/config.yaml or .bomly/config.yaml\n")
	for _, section := range sections {
		builder.WriteString("\n# " + section.name + "\n")
		for _, field := range section.fields {
			value := field.DefaultVal
			if value == "" {
				switch field.GoType {
				case "bool":
					value = "false"
				case "int":
					value = "0"
				case "string":
					value = "\"\""
				case "[]string":
					value = "[]"
				default:
					value = "\"\""
				}
			}
			builder.WriteString(fmt.Sprintf("# %s\n", field.Doc))
			builder.WriteString(fmt.Sprintf("# %s: %s\n", field.YAMLKey, value))
		}
	}
	builder.WriteString("```\n")

	return builder.String()
}

func configTypeString(expr ast.Expr) string {
	switch typed := expr.(type) {
	case *ast.Ident:
		return typed.Name
	case *ast.ArrayType:
		return "[]" + configTypeString(typed.Elt)
	case *ast.StarExpr:
		return "*" + configTypeString(typed.X)
	case *ast.SelectorExpr:
		return configTypeString(typed.X) + "." + typed.Sel.Name
	default:
		return "any"
	}
}

func toSnakeCase(value string) string {
	var result strings.Builder
	for idx, character := range value {
		if character >= 'A' && character <= 'Z' {
			if idx > 0 {
				result.WriteByte('_')
			}
			result.WriteByte(byte(character + 32))
			continue
		}
		result.WriteRune(character)
	}
	return result.String()
}
