package detectors

const (
	// NameNPM, NamePNPM, and NameYarn are the merged per-package-manager
	// detectors that own an internal lockfile→buildtool strategy order. The
	// historical lockfile/native names remain as registry aliases.
	NameNPM           = "npm"
	NameNPMLockfile   = "npm-detector"
	NameNPMNative     = "npm-native-detector"
	NamePNPM          = "pnpm"
	NamePNPMLockfile  = "pnpm-detector"
	NamePNPMNative    = "pnpm-native-detector"
	NameYarn          = "yarn"
	NameYarnLockfile  = "yarn-detector"
	NameBun           = "bun-detector"
	NameBunNative     = "bun-native-detector"
	NameYarnNative    = "yarn-native-detector"
	NameGradle        = "gradle-detector"
	NameMaven         = "maven-detector"
	NameGoMod         = "go-detector"
	NameComposer      = "composer-detector"
	NameBundler       = "bundler-detector"
	NameGitHubActions = "github-actions-detector"
	NamePip           = "pip-detector"
	NamePipenv        = "pipenv-detector"
	NamePoetry        = "poetry-detector"
	NameUV            = "uv-detector"
	NameNuGet         = "nuget-detector"
	NameCargo         = "cargo-detector"
	NamePub           = "pub-detector"
	NamePubNative     = "pub-native-detector"
	NameCocoaPods     = "cocoapods-detector"
	NameSwiftPM       = "swiftpm-detector"
	NameSwiftPMNative = "swiftpm-native-detector"
	NameMix           = "mix-detector"
	NameConan         = "conan-detector"
	NameSBT           = "sbt-detector"
	NameSBTNative     = "sbt-native-detector"
	NameSBOM          = "sbom-detector"
	NameSyft          = "syft-detector"
)
